require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6.6
  DisplayCopNames: true
  EnabledByDefault: true
  Exclude:
    - bin/*
    - vendor/ruby/**/*
    - node_modules/**/*
    - db/schema.rb
    - .licenses/**/*
    - config/**/*
Rails:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
Metrics:
  Exclude:
    - db/migrate/*
    - Rakefile
    - Gemfile
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*
Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/routes.rb
    - lib/tasks/**/*
    - spec/**/*
    - app/admin/**/*
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Layout:
  Exclude:
    - config/environments/*
Layout/LineLength:
  Max: 120
Style:
  Exclude:
    - spec/*_helper.rb
Style/BlockComments:
  Exclude:
    - config/**/*
    - spec/**/*
Style/Documentation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
